\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename triode.info
@settitle triode.el User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* triode.el: (triode).  TBD.
@end direntry

@finalout
@titlepage
@title triode.el User Guide
@subtitle for version 0.0.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top triode.el User Guide

Version: 0.0.1

Copyright © 2026 @w{Charles Y. Choi}

triode.el is TBD@.

If you enjoy using triode.el@comma{} please consider buying me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Features::
* Requirements::
* Install::
* Feedback & Discussion::
* Sponsorship::
* About::
* Acknowledgments::
* Main Index::
* Variable Index::
@end menu

@node Features
@chapter Features

@cindex Features

TBD

@node Requirements
@chapter Requirements

@cindex Requirements

TBD

@node Install
@chapter Install

@cindex Install

TBD

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about @strong{triode.el} to the @uref{https://github.com/kickingvegas/casual-suite/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using @strong{triode.el}@comma{} please join the @uref{https://github.com/kickingvegas/casual-suite/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

If you enjoy using triode.el@comma{} please consider buying me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@node About
@chapter About

@cindex About

@uref{https://github.com/kickingvegas/triode, triode.el} was conceived and crafted by Charles Y@. Choi in San Francisco@comma{} California.

Thank you for using @strong{triode.el}.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables@comma{} functions@comma{} commands@comma{} and menus referenced by this user guide.

@printindex vr

@bye
