\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename triode.info
@settitle triode.el User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* Triode: (triode).     An interface to the Triode app for macOS.
@end direntry

@finalout
@titlepage
@title triode.el User Guide
@subtitle for version 0.0.3-rc.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top triode.el User Guide

Version: 0.0.3-rc.1

Copyright © 2026 @w{Charles Y. Choi}


@image{images/triode-tmenu,,,,png}


@strong{triode.el} is a remote control interface to the Triode app (@uref{https://triode.app})@comma{} an internet radio station player for macOS@.

With @strong{triode.el}@comma{} you can control your listening to internet radio stations directly from GNU Emacs without need to change app focus.

If you enjoy using @strong{triode.el}@comma{} please consider buying me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Features::
* Requirements::
* Install::
* Usage::
* Feedback & Discussion::
* Sponsorship::
* About::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Usage

* Triode State Polling::

@end detailmenu
@end menu

@node Features
@chapter Features

@cindex Features

Remote control the Triode app from Emacs:

@itemize
@item
Choose station
@item
Play/Stop toggle
@item
Mute toggle
@item
Copy current station and track to clipboard
@item
Recognize music with Shazam
@item
Open Triode app
@end itemize

@node Requirements
@chapter Requirements

@cindex Requirements


@strong{triode.el} requires the following programs and Elisp packages:

@itemize
@item
macOS 15+ (Sequoia)  

@item
GNU Emacs 30.1+ (@ref{Top,,,emacs,})

@item
@uref{https://triode.app, Triode app} for macOS 2.4+

@item
@uref{https://github.com/kickingvegas/restlib, restlib} 0.1+

@item
@uref{https://github.com/kickingvegas/shazam, shazam.el} 0.1+
@end itemize

@node Install
@chapter Install

@cindex Install
@vindex triode-init

For manual installation@comma{} ensure that @code{triode.el} is available in the Emacs @code{load-path} variable.

This package requires the installation of a macOS Shortcut named “Triode RC JSON”. Download and install it in your library of Shortcuts by clicking on the link below:

@itemize
@item
@uref{https://www.icloud.com/shortcuts/0db0f47809fe4b0a84ac640846fd65ee, iCloud Shortcut: Triode RC JSON}
@end itemize

@strong{triode.el} by default requires your Emacs session to load the macOS SF Symbols font. Use the convenience function @code{triode-init} to setup both SF Symbols and to globally set your keybinding preference to the @code{triode-tmenu} command in your Emacs initialization file.

@lisp
(require 'triode) ;; optional if autoloaded
(triode-init "<f14>")
@end lisp

The use of the keybinding @kbd{<f14>} is merely a suggestion and can be changed to preference.

@node Usage
@chapter Usage

@cindex Usage
@vindex triode-tmenu
@vindex triode-dismiss-menu-for-actions


@image{images/triode-tmenu,,,,png}

Invoke the Transient menu @code{triode-tmenu} via @code{execute-extended-command} (@kbd{<f14>}) or by your preferred keybinding.

@example
M-x triode-tmenu RET
@end example


@code{triode-tmenu} offers the following menu items

@table @asis
@item @kbd{s}
Select station - open Triode app station selector to choose an internet radio station from your favorites list.

@item @kbd{@key{SPC}}
Play/Stop toggle to connect or disconnect to an internet radio station.

@item @kbd{m}
Muting toggle. This command does not disconnect an already connected internet radio station.

@item @kbd{r}
Refresh Triode app state (station@comma{} current track@comma{} playback state).

@item @kbd{w}
Copy current track to the clipboard (@code{kill-ring}).

@item @kbd{z}
Open @code{Shazam} music recognition. This requires @code{shazam.el} to be installed.

@item @kbd{o}
Open Triode app.

@item @kbd{@comma{}}
Open @code{triode.el} settings.

@item @kbd{@key{RET}}
Dismiss menu.
@end table

By default@comma{} most of the commands in @code{triode-tmenu} will keep the menu displayed. This behavior can be changed with setting the customizable variable @code{triode-dismiss-menu-for-actions} to @code{t}.

@menu
* Triode State Polling::
@end menu

@node Triode State Polling
@section Triode State Polling

@cindex Triode State Polling
@vindex triode-start-polling-status
@vindex triode-cancel-polling
@vindex triode-poll-status-interval

By default@comma{} @code{triode.el} will synchronize state between Emacs and the Triode app whenever a user action is taken. However@comma{} internet radio stations routinely can change metadata state (current track). While the Triode app can keep track of such changes@comma{} there is no capability for it to message such changes to Emacs.

A workaround is to have @strong{triode.el} periodically poll the Triode app to synchronize state. The following commands to support this are:

@deffn Command triode-start-polling-status
Start polling to synchronize Triode app state.
@end deffn

@deffn Command triode-cancel-polling
Stop polling to synchronize Triode app state.
@end deffn

The polling period is defined by the customizable variable @code{triode-poll-status-interval} (default 200 seconds).

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about @strong{triode.el} to the @uref{https://github.com/kickingvegas/triode/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using @strong{triode.el}@comma{} please join the @uref{https://github.com/kickingvegas/triode/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

If you enjoy using @strong{triode.el}@comma{} please consider buying me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@node About
@chapter About

@cindex About

@uref{https://github.com/kickingvegas/triode, triode.el} was conceived and crafted by Charles Y@. Choi in San Francisco@comma{} California.

Thank you for using @strong{triode.el}.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

Thanks to the makers of the Triode app@comma{} the Shortcuts team@comma{} and to the GNU Emacs contributors from which @strong{triode.el} builds from. This work would not be possible without your efforts.

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables@comma{} functions@comma{} commands@comma{} and menus referenced by this user guide.

@printindex vr

@bye
